{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wseemann",
    "module": "roku-ecp-wrapper-kotlin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "roku-ecp-wrapper-kotlin-1.3.0.jar",
          "url": "roku-ecp-wrapper-kotlin-1.3.0.jar",
          "size": 59191,
          "sha512": "ccad054dcb95155235894dc25e741a4e27d37784f5983c189731bac27f33a6257fa7728e3c4cf3a363874a9b70da1a90384259fe21cd6fef754a6fc6e903790e",
          "sha256": "8fd002da18d55636df69f428fb5fe64916e1b38b78ef031f88c92ca05adc262a",
          "sha1": "15ec23464681eb5a1f9ca8516c48a6cf236d3a79",
          "md5": "08d766d9964bcabee918b0fca8ca0c68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "roku-ecp-wrapper-kotlin-1.3.0.jar",
          "url": "roku-ecp-wrapper-kotlin-1.3.0.jar",
          "size": 59191,
          "sha512": "ccad054dcb95155235894dc25e741a4e27d37784f5983c189731bac27f33a6257fa7728e3c4cf3a363874a9b70da1a90384259fe21cd6fef754a6fc6e903790e",
          "sha256": "8fd002da18d55636df69f428fb5fe64916e1b38b78ef031f88c92ca05adc262a",
          "sha1": "15ec23464681eb5a1f9ca8516c48a6cf236d3a79",
          "md5": "08d766d9964bcabee918b0fca8ca0c68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roku-ecp-wrapper-kotlin-1.3.0-sources.jar",
          "url": "roku-ecp-wrapper-kotlin-1.3.0-sources.jar",
          "size": 24564,
          "sha512": "7edd07cf1afbb1d03a1e9fd1baedf909040fad157d1e57ffc6ff86ab753b8a70ace006276bba66909bb6118e633022b988e9c40e375c152f2de2833e847176e8",
          "sha256": "c4ac328cab88f0a58ca6e7a610d44edc37d7ace5b3369274dd373a3d708c2a9c",
          "sha1": "a09a66e253466c563540bd5da57efc893dd21961",
          "md5": "1a1b44386946dd80c427850cece63777"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roku-ecp-wrapper-kotlin-1.3.0-javadoc.jar",
          "url": "roku-ecp-wrapper-kotlin-1.3.0-javadoc.jar",
          "size": 229801,
          "sha512": "735978b6574a0524458901235d6ed8269475fc8fc471804874f961b63e9e7f8a38b75b848cfdab60152fe56b874e898050a28ac06c8c38a23328b7279c57a48f",
          "sha256": "acbc4659cecc25426419cc2127c4dcefa4d0123f30f15dd498c1596bc4562a0d",
          "sha1": "fe077a8743194febb0019fbff4bb49be087232c5",
          "md5": "9199ae04b539ea91f2336812532be6e6"
        }
      ]
    }
  ]
}
