[versions]
aboutlibraries = "14.2.1"
androidx-activity-compose = "1.13.0"
androidx-appcompat = "1.7.1"
androidx-lifecycle = "2.8.7"
androidx-preference = "1.2.1"
androidx-splashscreen = "1.0.1"
android-material = "1.12.0"
coil = "3.3.0"
compose-bom = "2026.06.01"
detekt = "2.0.0-alpha.6"
hilt = "2.60.1"
jdom = "2.0.6"
kotlinx-collections-immutable = "0.5.2"
play-review = "2.0.2"
roku-ecp-wrapper-kotlin = "1.5.0"
timber = "5.0.1"
junit = "4.13.2"

[libraries]
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
jdom = { module = "org.jdom:jdom2", version.ref = "jdom" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "play-review" }
roku-ecp-wrapper-kotlin = { module = "com.github.wseemann:roku-ecp-wrapper-kotlin", version.ref = "roku-ecp-wrapper-kotlin" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
aboutlibraries-android = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
