apply plugin: 'com.android.application'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'com.mikepenz.aboutlibraries.plugin.android'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    namespace = "wseemann.media.romote"

    signingConfigs {
        create("releaseConfig") {
            storeFile file('/Users/wseemann/Downloads/keystore')
            storePassword 'xxxxxxxxXX'
            keyAlias 'mykey'
            keyPassword 'xxxxxxxxXX'
        }
    }

    defaultConfig {
        applicationId "wseemann.media.romote"
        minSdkVersion 26
        targetSdk 35
        compileSdk 36
        versionCode 29
        versionName "1.0.29"
    }
    buildTypes {
        getByName("release") {
            signingConfig = signingConfigs.getByName("releaseConfig")
            minifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }
    buildFeatures {
        buildConfig = true
        aidl = true
        compose = true
    }
}

aboutLibraries {
    collect.fetchRemoteLicense = false
    collect.fetchRemoteFunding = false
    export.excludeFields = ["generated", "developers", "funding"]
}

dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.aar', '*.jar'], exclude: [])
    implementation(libs.aboutlibraries.compose.m3)
    implementation(platform(libs.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.legacy)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.preference)
    implementation(libs.androidx.splashscreen)
    implementation(libs.android.material)
    implementation(libs.compose.material.icons.core)
    implementation(libs.compose.material3)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.glide)
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.jdom)
    implementation(libs.kotlinx.collections.immutable)
    implementation(libs.roku.ecp.wrapper.kotlin)
    implementation(libs.timber)

    debugImplementation(libs.compose.ui.tooling)

    testImplementation(libs.junit)
}